[
  {
    "description": "",
    "elements": [
      {
        "after": [
          {
            "match": {
              "location": "support/ruby/env.rb:5"
            },
            "result": {
              "duration": 126000,
              "error_message": "Failing after hook (RuntimeError)\n./support/ruby/env.rb:6:in `After'",
              "status": "failed"
            }
          }
        ],
        "description": "",
        "id": ";",
        "keyword": "Scenario",
        "line": 3,
        "name": "",
        "steps": [
          {
            "keyword": "Given ",
            "line": 4,
            "match": {
              "location": "support/ruby/env.rb:13"
            },
            "name": "this step passes",
            "result": {
              "duration": 40000,
              "status": "passed"
            }
          }
        ],
        "tags": [
          {
            "line": 2,
            "name": "@failing-after"
          }
        ],
        "type": "scenario"
      },
      {
        "after": [
          {
            "match": {
              "location": "support/ruby/env.rb:5"
            },
            "result": {
              "duration": 245000,
              "error_message": "Failing after hook (RuntimeError)\n./support/ruby/env.rb:6:in `After'",
              "status": "failed"
            }
          }
        ],
        "description": "",
        "id": ";",
        "keyword": "Scenario",
        "line": 3,
        "name": "",
        "steps": [
          {
            "keyword": "Given ",
            "line": 4,
            "match": {
              "location": "support/ruby/env.rb:13"
            },
            "name": "this step passes",
            "result": {
              "duration": 21000,
              "status": "passed"
            }
          }
        ],
        "tags": [
          {
            "line": 2,
            "name": "@failing-after"
          }
        ],
        "type": "scenario"
      },
      {
        "after": [
          {
            "match": {
              "location": "support/ruby/env.rb:5"
            },
            "result": {
              "duration": 145000,
              "error_message": "Failing after hook (RuntimeError)\n./support/ruby/env.rb:6:in `After'",
              "status": "failed"
            }
          }
        ],
        "description": "",
        "id": ";",
        "keyword": "Scenario",
        "line": 3,
        "name": "",
        "steps": [
          {
            "keyword": "Given ",
            "line": 4,
            "match": {
              "location": "support/ruby/env.rb:13"
            },
            "name": "this step passes",
            "result": {
              "duration": 14000,
              "status": "passed"
            }
          }
        ],
        "tags": [
          {
            "line": 2,
            "name": "@failing-after"
          }
        ],
        "type": "scenario"
      }
    ],
    "id": "",
    "keyword": "Feature",
    "line": 1,
    "name": "",
    "uri": "examples/single/failing-after-hook.feature"
  }
]
